### ISSUE TITLE
invalid qrcode

### ISSUE THREAD

**Issue by bcookatpcsd** [markeclaudio/mikrotik-wireguard-config-generator#1]
Thank you for taking the time to make this.. greatly appreciated. 

It seems that the rendered qrcode does not import into iOS wireguard. 

1.0.16 (27) 

![image](https://github.com/markeclaudio/mikrotik-wireguard-config-generator/assets/55087301/0a6ad4b9-fc85-4918-912b-cee51711c90e)

Load the interface, change clients to 1, click generate.. 

![image](https://github.com/markeclaudio/mikrotik-wireguard-config-generator/assets/55087301/9446b873-459e-4fd9-b121-306396e03e29)

I was also unable to download the client config on my actual configuration.. but it seems in this sampling I was able to.. 

Hmm, it looks like when you click anything else.. the focus never goes back to the client conf download.. (not sure if that makes sense.. ) 

Please let me know if I can help further..

**Comment by markeclaudio** [comment]
Fixed with latest commit
