### ISSUE TITLE
preshared-key (string; Default: ) for more Security in Connetcions

### ISSUE THREAD

**Issue by dawdad** [markeclaudio/mikrotik-wireguard-config-generator#3]
Hi,

Is it possible for you to add a **preshared key** option to your script and awesome generator?

As according to the MT wiki it would increase the security for client connections:

_A base64 preshared key. Optional, and may be omitted. This option adds an additional layer of symmetric-key cryptography to be mixed into the already existing public-key cryptography, for post-quantum resistance._
https://help.mikrotik.com/docs/display/ROS/WireGuard

Br,
dawdad

**Comment by mustaphazorgati** [comment]
Hi @markeclaudio! @dawdad and I have added this functionality to your existing project. Would you mind taking a look at the PR and maybe integrating it?

Cheers!

**Comment by markeclaudio** [comment]
Merged! I really appreciate

**Comment by markeclaudio** [comment]
Merged
