### ISSUE TITLE
Download buttons not working

### ISSUE THREAD

**Issue by blue-yu** [markeclaudio/mikrotik-wireguard-config-generator#7]
Hello,
Both download buttons are not working. Nothing happend then i click them. Testing on Chrome and Edge.

**Comment by mustaphazorgati** [comment]
Hi @markeclaudio! I fixed this in #8. Can you take a quick look at it? 

Since it's a one-liner, it shouldn't take long :)

**Comment by markeclaudio** [comment]
Thanks, I merged
